### ISSUE TITLE
Secure QR image

### ISSUE THREAD

**Issue by rolero** [BrandonPotter/GoogleAuthenticator#1]
I noticed that the url generated by QrCodeSetupImageUrl is not secure. Created a workaround: string.Replace("http","https"). Maybe it is an options to add an method called:  QrCodeSetupImageUrlSecure

**Comment by BrandonPotter** [comment]
This was recently added, see last parameter on:

public SetupCode GenerateSetupCode(string issuer, string accountTitleNoSpaces, string accountSecretKey, int qrCodeWidth, int qrCodeHeight, bool useHttps)

Is that what you're looking for?

**Comment by rolero** [comment]
Thanks. I did not see.
