### ISSUE TITLE
Remove Uri.EscapeUriString

### ISSUE THREAD

**Issue by flytzen** [BrandonPotter/GoogleAuthenticator#103]
https://github.com/BrandonPotter/GoogleAuthenticator/blob/c464ba3a70a16d3ec9f30b936c3cfafb02751879/Google.Authenticator/TwoFactorAuthenticator.cs#L63

`EscapeUriString` is [obsolete from .Net 6.0](https://docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0013). However, it's recommended replacement `EscapeDataString` changes the output. Specifically, it changes "a@b.com" becomes "a%40b.com".

For now, we are ignoring the warning, but this should be understood more deeply and fixed at some point.

**Comment by ahwm** [comment]
@flytzen I actually just saw something about that in a PR - codebude/QRCoder#391

Based on tests there, looks like it should be `a%40b.com`

**Comment by flytzen** [comment]
> @flytzen I actually just saw something about that in a PR - [codebude/QRCoder#391](https://github.com/codebude/QRCoder/pull/391)
> 
> Based on tests there, looks like it should be `a%40b.com`

Interesting. Problem is, that would probably be a breaking change so we would need to handle it carefully, at least.
