### ISSUE TITLE
Change supported framework versions

### ISSUE THREAD

**Issue by flytzen** [BrandonPotter/GoogleAuthenticator#107]
Change supported framework versions to align with what is now supported. Maybe move to netstandard 2.0 to keep it simple.

See #106 for discussions about framework versions

- [X] The Unit Test project should explicitly support a wide range of specific versions to ensure we test that it actually works.
- [X] Remove the `#if`  and the declaration of framework specific constants from the main package
- [X] Test the two sample projects still work

**Comment by flytzen** [comment]
@ahwm Shall we try to just target netstandard2.0 in the main package but have the unit tests target 4.61 and various others? We can always add explicit support for other frameworks in the main package if any of the tests fail.

**Comment by ahwm** [comment]
> @ahwm Shall we try to just target netstandard2.0 in the main package but have the unit tests target 4.6.2 and various others? We can always add explicit support for other frameworks in the main package if any of the tests fail.

That works for me.
