### ISSUE TITLE
GenerateSetupCode starts throwing GDI+ errors after a random period

### ISSUE THREAD

**Issue by MarkHeddaeus** [BrandonPotter/GoogleAuthenticator#119]
Hi, Thanks for writing an maintaining this! It does exactly what we need, except when it doesn't.

We're using this in a web app for 2FA. It runs fine for a random time period, but then starts throwing GDI+ errors for all calls to GenerateSetupCode. The first time, it only ran for about an hour with low volume. The second time it ran for 3 days with periods of high volume (5000 calls in a minute). The only thing that solves the problem is to reset the site in IIS.

I've watched TaskManager when generating the codes. The memory usage jumps while it's processing, but then drops back down, so doesn't seem like a memory leak.

Here's the code we're using (the real code only makes one call, of course, but this is what I've been testing with):
```
int qrCodeCount = 100;

for (int i = 0; i < qrCodeCount; i++)
{
	string key = Guid.NewGuid().ToString().Replace("-", "").Substring(0, 10);

	TwoFactorAuthenticator tfa = new TwoFactorAuthenticator();
	SetupCode setupInfo = tfa.GenerateSetupCode("Test Portal", "SAMPLE" + key, key, false, 3);
	if (setupInfo != null)
	{
		System.Web.UI.WebControls.Image img = new System.Web.UI.WebControls.Image();
		img.ImageUrl = setupInfo.QrCodeSetupImageUrl;
		//lblManualSetupCode.Text = setupInfo.ManualEntryKey;
		phQRCodes.Controls.Add(img);
	}
}
```
And the exception:
```
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.    
 at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)    
 at Google.Authenticator.TwoFactorAuthenticator.GenerateQrCodeUrl(Int32 qrPixelsPerModule, String provisionUrl)    
 at Google.Authenticator.TwoFactorAuthenticator.GenerateSetupCode(String issuer, String accountTitleNoSpaces, Byte[] accountSecretKey, Int32 qrPixelsPerModule, Boolean generateQrCode)    
 at TopLineGroup.Web.Admin_OtherSiteMaintenance.lbTestMFAQRCodes_Click(Object sender, EventArgs e) in E:\...\OtherSiteMaintenance.aspx.cs:line 207
```

**Comment by ahwm** [comment]
Can you confirm which version you're using and what .NET version you're running on?

**Comment by MarkHeddaeus** [comment]
Sorry, meant to include that.
v2.4.0 with .Net framework 4.8

**Comment by ahwm** [comment]
Unfortunately, I've been unable to duplicate this. I set it up as a console app first, ran it a few times at 1000 and a few times at 100. Then I created a new Web Forms project and generated 100 and 1000 a few times each. Then added a link button to generate 100 at a time and got no errors.

Leads me to believe it's got something to do with your application that it's part of or something to do with running under IIS which I'll test myself in a bit. If you have a sandbox environment would you be able to try out [3.0.0-beta1](https://www.nuget.org/packages/GoogleAuthenticator/3.0.0-beta1) as an experiment? It removes the reliance on `System.Drawing`.

**Comment by MarkHeddaeus** [comment]
I get pretty much the same thing. Generating blocks of 100 at a time have no problem. It just randomly stops working at some point.

I have it running with the beta in a test environment now. I'll periodically generate 100 or so and see if it breaks.

**Comment by MarkHeddaeus** [comment]
So far so good with the beta. 

I ran it manually on Friday and this morning with 100 codes every hour or so. And today I set it up to automatically refresh every 10 seconds, and I'm running it simultaneously in 15 tabs over 3 browsers with no problems.

How close it the beta to release? I'd like to try it in our live site, but if there are other known issues...

**Comment by ahwm** [comment]
@flytzen Anything else we waiting on for the beta? I think that was the primary change aside from the TFMs. Oh and possibly cleaning up some of the encoding stuff right?

**Comment by flytzen** [comment]
> @flytzen Anything else we waiting on for the beta? I think that was the primary change aside from the TFMs. Oh and possibly cleaning up some of the encoding stuff right?
> 
> I'd say that sounds like it's had a pretty good test run otherwise.

It's only the encoding thing, which may only have a small UI impact if you have non-alpanumerics in your issuer name. If not, beta 1 is ready for production. 
I'll prioritise getting the encoding done, but that should go through a short beta 2 phase.
I would recommend you put beta 1 into production 😉

**Comment by ahwm** [comment]
Beta2 is up.
