### ISSUE TITLE
A strongly-named assembly is required

### ISSUE THREAD

**Issue by munagalap** [BrandonPotter/GoogleAuthenticator#123]
Hello,

We are using strong names assemblies in my project, when i plug in Google.Authenticator package in my solution, I am getting bellow error when executing the application. (compiling is fine)

Could not load file or assembly 'Google.Authenticator, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Can you please provide the strong names assembly?

Thanks,
Purushothama Reddy M

**Comment by ahwm** [comment]
I've seen this handled a few different ways by other libraries.

- Sign main lib
- Create separate package for signed libraries
- Leave it up to the consuming project to sign libraries during their own build/publish process (probably not *preferred* method as it doesn't "just work")

@flytzen @BrandonPotter do either of you have a preference? I know .NET has been moving away from the notion of strong named libraries in general except in very specific circumstances (such as VS extensions) where it needs to be installed in the GAC, but this would be a relatively easy update to make I think.

**Comment by ahwm** [comment]
I think the third option I mentioned above is probably the direction you're wanting to go, then. If our preference is not to sign it ourselves at all then they would need to configure their own build step that signs it. They could do that during the build of their project and wouldn't *necessarily* have to fork the project, which would add some maintenance commitments.

**Comment by munagalap** [comment]
Hello @ahwm,
Thanks for the response.

I heard that you are not planning to provide strong named assembly, so can you please guide us how can we use this package in strong named projects?

Currently, I have downloaded the code from GIT hub and replicated and singed in my local and published as a nuget package. It working fine now, but my company doesn't allow to publish third party code.
Please describe the steps handle the build process to make it work.
