### ISSUE TITLE
Not an issue but I have questions

### ISSUE THREAD

**Issue by 1fini** [BrandonPotter/GoogleAuthenticator#131]
Hi guys, 

First, I would like to say thanks to the developers and maintainers of this repo. 
Then, I was willing to use this library in my project and I came across a few questions while seeing the results. 

Let me explain my use case. 
I want to be able to connect to my Instagram account from my .net 6 application. 
So if I understand well, I juste need to use the key provided by Instagram (key that I can insert into the google authenticator app and that gives me the pin code). 
If I use that exact same key (32 digits) with the function : GetCurrentPIN(string accountSecretKey, DateTime now, bool secretIsBase32 = false)
It then gets validated with ValidateTwoFactorPIN(...) because it returns true. But when I use the pin code, the authentication gets rejected by instagram login method. 
I don't know if there's a problem with my logic or if there is something else that I do wrong.

All ideas are welcome.

**Comment by flytzen** [comment]
I think this is probably the wrong library for that: This lib is designed for you to implement 2FA in your own application, not to generate client-side codes for use on another site. 
For that use-case, by all means look at the code here, but write your own implementation. 
At a guess, you may be running into issues about how the secret is encoded and decoded. The underlying secret is a byte[]. This library gives you convenience methods for handling this in your server-side code, where you are handling the secret yourself. You'd need to figure out the format the key is sent to the client and then correctly convert that back to a byte array[] before passing it into the methods to calculate the pin. The methods in this lib that accepts `string` are convenience methods that make explicit assumptions about how you have stored the `byte[]` in your system and they are probably not the same as what is sent to the client.

**Comment by 1fini** [comment]
Thanks for you input @flytzen

Best regards.
