### ISSUE TITLE
Name of the repo

### ISSUE THREAD

**Issue by 1Jesper1** [BrandonPotter/GoogleAuthenticator#133]
Why is the repo named GoogleAuthenticator, since it could also be used with Authy and Microsoft authenticator?
My suggestion is to change the repo name to TOTPAuthenticator (Time based one time password), although the current name would be a better catch, since most people search for Google Authenticator. :)

**Comment by flytzen** [comment]
@1Jesper1 
You are not wrong :) 
It's just one of those accidents of history and I suspect that if we were to change it now, it would cause too much confusion.
