### ISSUE TITLE
Unsafe secret generation

### ISSUE THREAD

**Issue by RobThree** [BrandonPotter/GoogleAuthenticator#146]
As per [your README](https://github.com/BrandonPotter/GoogleAuthenticator/blob/a68a124d2f20f72eb8d59a12ad3f72ba852e47a6/README.md?plain=1#L18):

```c#
string key = Guid.NewGuid().ToString().Replace("-", "").Substring(0, 10);
```

[GUIDs are designed to be unique, not random](https://devblogs.microsoft.com/oldnewthing/20120523-00/?p=7553). So this is NOT a good idea. The code should be any BASE32 string (2-9, A-Z, excluding O/L), however your method only produces (0-9, A-F). You're losing half the possible values.

Also, you're using only 10 characters, 80 bits. As per [RFC4226](https://www.rfc-editor.org/rfc/rfc4226):

> R6 - The algorithm MUST use a strong shared secret.  The length of the shared secret MUST be at least 128 bits.  This document RECOMMENDs a shared secret length of 160 bits.

So you're also dropping another 80 bits of entropy there (half(!) of the recommended). This makes the secret MUCH easier to guess / brute force if one or a few "PINs" are known. Your method only uses 25% of the available entropy by my calculations.

**Comment by ahwm** [comment]
Shown as example for illustration purposes only. Developer is expected to have experience and understand best practices of key generation, which is not handled by the library.

Thanks for your interest!

**Comment by RobThree** [comment]
The problem with examples is that people tend to copy and paste them. Especially assuming people 'to have experience and understand best practices of key generation'; there's lots of inexperienced people, some just don't know any better. People may assume the provided code is safe. People may assume the library 'handles' it or people may assume it's good enough.

At the very least a warning would be advisable. But better yet, why not simply provide good (or at least better) code from the get go that _is_ usable for real life usage?

Especially since you already have [an overload that takes a `byte[]` for a key](https://github.com/BrandonPotter/GoogleAuthenticator/blob/c6a21651e99264cfb8429f8e555326f42deb78bb/Google.Authenticator/TwoFactorAuthenticator.cs#L54), why not use this in your Readme?

```c#
using System.Security.Cryptography;

string key = RandomNumberGenerator.GetBytes(20);
```

This provides the recommended amount of bits of entropy and [is cryptographically secure](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.randomnumbergenerator.getbytes?view=net-7.0#system-security-cryptography-randomnumbergenerator-getbytes(system-int32)). And so much better than:

```c#
string key = Guid.NewGuid().ToString().Replace("-", "").Substring(0, 10);
```

It's even shorter and more readable too! 😉
