### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by Serjster** [BrandonPotter/GoogleAuthenticator#15]
Is there a .NET Core version of this? Or planned?

**Comment by Allen4Tech** [comment]
Any plan for supporting .NET Core?

**Comment by Serjster** [comment]
Don't think it's actually needed. I just copy/pasted the files in the GoogleAuthenticator folder to my .NET Core project and it all worked.

**Comment by Allen4Tech** [comment]
@Serjster I will have a try, thanks!

**Comment by JonHanna** [comment]
It would be nice just to have it listed as compatible in nuget, to stop the compatibility warning.

**Comment by elsauto** [comment]
I am working on .net portability right now. I did no production environment testing but it is working smoothly by now. Sorry if this thread is already forgotten.

**Comment by hjkl950217** [comment]
I also copy directly
only copy tow file:
1.SetupCode.cs
2.TwoFactorAuthenticator.cs

**Comment by AyrA** [comment]
You can just install (currently 1.2.1) via nuget and it will work just fine. It logs this warning into the console though:

> Package 'GoogleAuthenticator 1.2.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.

In other words, for this to continue to work, the author just has to add the .NET Core version number to the list of supported frameworks.

**Comment by ahwm** [comment]
@AyrA you are correct. As long as your project will be on a Windows machine with the full framework installed it will work just fine. But your project will not be portable to other systems. I have a PR to address this, but it hasn't been reviewed as yet.

**Comment by BrandonPotter** [comment]
I really do need to get this merged so this lib converts over to .NET Standard, just haven't had the time to redo the build/nuget package process in AppVeyor to go along with the PR. If any contributors would like to address that and save me the time then we can certainly get this up to .NET Standard, otherwise maybe I can address it over Christmas vacation.

**Comment by ahwm** [comment]
@BrandonPotter let me know how I can help and I'll do what I can. :)

**Comment by flytzen** [comment]
@BrandonPotter I don't know AppVeyor but very happy to set up the build pipeline in Azure Dev Ops if you are up for the move?

**Comment by BrandonPotter** [comment]
@flytzen @ahwm more than happy to add you both to devops to sort out package/publish - that will go a long way toward getting some of the outstanding req's in this library completed... give me a few mins to get the project set up

**Comment by BrandonPotter** [comment]
@ahwm what's a good email for you (devops invite) - for some reason github user search is supposed to work but it is not

**Comment by ahwm** [comment]
@BrandonPotter adam@adamh.us

**Comment by BrandonPotter** [comment]
cool - see if you both have github and devops permissions now

**Comment by ahwm** [comment]
I do have GitHub permissions, but I don't seem to have any access in Azure. I'll check back in a couple of hours and see if I get an email invite or anything.

**Comment by BrandonPotter** [comment]
https://dev.azure.com/brandon-potter/GoogleAuthenticator

**Comment by flytzen** [comment]
Hi,

Thanks for this Brandon.
Sorry, timezones etc.

My emails if flytzen@neworbit.co.uk<mailto:flytzen@neworbit.co.uk>.

Frans

**Comment by flytzen** [comment]
In terms of getting this set up; I can set up an Azure pipeline this weekend if you want? 
Once that's up, it should run the tests etc on each PR and then you can choose whether to merge in @ahwm PR for .Net standard?
To actually push the package to Nuget we'll need to set up some creds on AzDO for that, but that's easy enough.

**Comment by BrandonPotter** [comment]
Well, today the github search is working to invite members - so that is done.

If you are able to get the pipeline to the point that you need nuget creds, let me know and I can pop those in.

My preference would certainly be to merge the PR and get this library compatible with .NET standard, with a major version increment.

**Comment by ahwm** [comment]
I’ve updated my PR to change the version. :)

**Comment by flytzen** [comment]
@BrandonPotter Firstly, apologies; I was floored by a migraine this weekend so was unable to progress this. Secondly, AzDO and GitHub between them seems to be confused so I can't get access to the AzDO account. Are you able to invite my flytzen at neworbit.co.uk account directly? 
Thank you :)

**Comment by BrandonPotter** [comment]
@flytzen invited directly, let me know if that worked

**Comment by flytzen** [comment]
@BrandonPotter  yes, got it, thank you. That'll be my Christmas project now :)
