### ISSUE TITLE
Release 3.1

### ISSUE THREAD

**Issue by RomanSoloweow** [BrandonPotter/GoogleAuthenticator#152]
What about next release

**Comment by ahwm** [comment]
Pending #143 - I've pinged @BrandonPotter to get it updated but he's been busy so still waiting on that. Once that's done then it will go out.

**Comment by ahwm** [comment]
Pushed to Nuget. You should be able to install it shortly!

**Comment by RomanSoloweow** [comment]
Great news! Thank you
