### ISSUE TITLE
Change Organization Image/Title that gets imported into authenticator app?

### ISSUE THREAD

**Issue by SCLDGit** [BrandonPotter/GoogleAuthenticator#153]
Is there a way to alter these properties so that when a user loads the QR code into an authenticator app they don't just see "Third-Party" listed as the account type?

**Comment by ahwm** [comment]
I think that typically depends on what you call the account in your auth link. What app are you using?

**Comment by SCLDGit** [comment]
I had tested with Duo. Typically when scanning in a new QR code the new authenticator registers itself as a named app (for example, GitHub shows up with the GitHub logo and name). When I scan a code generated with Issuer as MyCompanyName and account as MHeimlich, the authenticator registers as a generic app called Third Party with no logo.

Thanks,

Matt
________________________________

**Comment by ahwm** [comment]
You'll need to reach out to DUO. It is based on the issuer/account name - https://help.duo.com/s/article/5706?language=en_US

That's really outside the scope of this library.

**Comment by SCLDGit** [comment]
Yep, after more research it would seem this is an issue solely with Duo not conforming to any standards in its authenticator app. Sorry for the confusion!

________________________________
