### ISSUE TITLE
Only works with 6-digit codes

### ISSUE THREAD

**Issue by JonHanna** [BrandonPotter/GoogleAuthenticator#16]
Whenever I've tried to set the code length in my authenticator app to be larger than 6 digits the verification seems to fail. It doesn't seem to be a timing issue as it does work consistently with 6-digit codes.

**Comment by ahwm** [comment]
Google Authenticator (and most other implementations) only support 6 digits. The only one I know of that supports longer ones is [Authy](https://www.authy.com) and it's a custom implementation by them that is not supported by anyone else.
