### ISSUE TITLE
Bug in ValidateTwoFactorPIN

### ISSUE THREAD

**Issue by WolframCrem** [BrandonPotter/GoogleAuthenticator#162]
Hello

I just found a bug (i think) in the ValidateTwoFactorPIN method

when i try to validate with 718761 for example it says its valid but when i do 718 761 it is not,
but 718761 is indeed invalid so it also should return false in the method when there is no space between the middle.

this is my code i used for testing

```
using Google.Authenticator;

string key = "fefesfef";

TwoFactorAuthenticator tfa = new TwoFactorAuthenticator();
SetupCode setupInfo = tfa.GenerateSetupCode("Test Two Factor", "user@example.com", key, false, 3);
Console.WriteLine(key);
Console.WriteLine(setupInfo.QrCodeSetupImageUrl);
Console.WriteLine(setupInfo.ManualEntryKey);

var result = tfa.ValidateTwoFactorPIN(key, "718761");
Console.WriteLine(result);
```

if you need more info i'm willing to help

**Comment by flytzen** [comment]
Hi @WolframCrem 

If I understand what you are saying, then you get `true` when you try to validate the code "718761". That should obviously not happen.

I believe your question can be reduced down to this (as all the stuff about setup is irrelevant):
```
    [Fact]
    public void TestKey718761()
    {
        string key = "fefesfef";
        var subject = new TwoFactorAuthenticator();

        var result = subject.ValidateTwoFactorPIN(key, "718761");

        result.ShouldBeFalse();
    }
```

Is that right?

Thing is, that test passes. 
In your example, the last thing that is printed should be `false`. 

Did you choose "718761" by random or did you get it from a two factor app? If the latter, it will stay valid for five minutes.

I have ignored the thing about the space in the middle: This library will not strip out spaces for you, you need to do it yourself, so I think that is irrelevant :)

**Comment by WolframCrem** [comment]
Yes the number came from my Authenticator app but was expired when I tried it

**Comment by WolframCrem** [comment]
weird, now it returns always false even when the code is still valid in the app, both google and microsoft. 
both with and without a space in the middle
