### ISSUE TITLE
GenerateSetupCode is called with secretIsBase32=true, but the AccountSecretKey and ManualEntryKey are different

### ISSUE THREAD

**Issue by meyerlee** [BrandonPotter/GoogleAuthenticator#191]
// test v3.1.1
string key = "HAHAH";
TwoFactorAuthenticator tfa = new TwoFactorAuthenticator();
SetupCode setupInfo = tfa.GenerateSetupCode("test", "test", key, true, 3);   
Console.WriteLine("key:{0} ManualEntryKey:{1}", key, setupInfo.ManualEntryKey);

The result is “key: HAHAH ManualEntryKey:HAHAG”, not “key: HAHAH ManualEntryKey:HAHAH”. Is this a bug?
![1702457244367](https://github.com/BrandonPotter/GoogleAuthenticator/assets/8414971/355cdf71-f368-42b8-93ef-4ac379696bdf)

**Comment by ahwm** [comment]
This will require some investigating.

**Comment by ahwm** [comment]
@flytzen maybe you have some additional insight here? It seems when `Base32Encoding.ToBytes()` runs on "HAHAH" it returns a `byte[]` with the values `{ 56, 14, 3 }` but when you pass that array back into `Base32Encoding.ToString()` you get back "HAHAG=="

My best guess is that "HAHAH" isn't a valid base32-encoded string.

When I use "HAHAH" as the key and specify that it's not base32 then I get a setup code of "JBAUQQKI".

If I use JBAUQQKI and specify that it is already base32 then I get an array of `{ 72, 65, 72, 65, 72 }` which converts back to JBAUQQKI as expected.

**Comment by flytzen** [comment]
'"' is a filler character that is routinely omitted from base32/base64 encoded values. In principle most code should work the same whether you include or exclude them. 
I'll have a look when I can get to my computer 👍

**Comment by flytzen** [comment]
@ahwm is right: `HAHAH` is not a valid Base32 encoded string. You can see the same behaviour on https://cryptii.com/pipes/base32. 

You need to start with a byte array and then convert that to Base32 to get a string that is valid.

The best way to get a secret key for a user (the secret must be unique per user) is like this: `System.Security.Cryptography.Aes.Create().Key`.
That will give you a byte array. You can then either base64 encode that yourself for storage, or you can grab the Base32 encoded key from the `SetupCode` object and store that in your database.
