### ISSUE TITLE
Reason to upgrade from 2.1.1

### ISSUE THREAD

**Issue by aaronhudon-pq** [BrandonPotter/GoogleAuthenticator#192]
This is more of a question than an issue - I don't see a discussion area for this project.

I've been using v2.1.1 since May of 2020 in a production environment using .NET 4x.  It's been working perfectly for thousands of users.

There's been a lot of chatter since then, and version updates.  What sort of benefit would I see with an update?

**Comment by ahwm** [comment]
.NET Framework-based projects probably won't see many benefits as most of the updates have been geared toward support for .NET Core/.NET 5+.

However, there have been a few corner case bugs that have been addressed and a few tweaks to secret handling.

Full list: https://github.com/BrandonPotter/GoogleAuthenticator/compare/2.1...v3.1
