### ISSUE TITLE
Update HMAC SHA

### ISSUE THREAD

**Issue by capegreg** [BrandonPotter/GoogleAuthenticator#197]
Can SHA in GenerateHashedCode be updated from HMACSHA1 to HMACSHA256?

**Comment by ahwm** [comment]
This is in progress, but as noted on #198 a number of popular OTP apps don't support SHA256 including: Microsoft Authenticator and Authy so it's probably not recommended unless you can control the apps being used to some extent.

Given the location where the HMAC is generated there doesn't appear to be a big push or concern (it's only used to generate the time codes).

**Comment by capegreg** [comment]
Understood and agree with you regarding its isolated use. Interesting that some OTP apps don't support SHA256 yet. Microsoft Authenticator is one of my supported OTP apps. Thank you, Adam.

**Comment by capegreg** [comment]
Closing issue.

**Comment by flytzen** [comment]
@capegreg FYI: @ahwm made the change and v 3.2 is on its way to Nuget with this added.

Thank you both.
