### ISSUE TITLE
the blog link is broken

### ISSUE THREAD

**Issue by 1906sam** [BrandonPotter/GoogleAuthenticator#21]
this link is broken: http://brandonpotter.com/2014/09/07/implementing-free-two-factor-authentication-in-net-using-google-authenticator/

**Comment by PhonicUK** [comment]
There's a mirror here: https://csharprookie.wordpress.com/2015/03/17/implementing-free-two-factor-authentication-in-net-using-google-authenticator/

**Comment by iivmok** [comment]
@BrandonPotter could you add the documentation to the readme?

**Comment by ahwm** [comment]
I've started adding some information to the wiki. You're welcome to help out with that!
