### ISSUE TITLE
Two factor code from client does not get expired once used for validation

### ISSUE THREAD

**Issue by sanasz91mdev** [BrandonPotter/GoogleAuthenticator#22]
Using the same two factor code from client to validate (more then once) via ValidateTwoFactorPIN validates successfully whereas the code should be expired once used.

It expired only after the given time is lapsed. ... i.e. if time lapse was 30 seconds and i validate same two factor code from client more then once within 30 seconds, it will always give me success where as once used, it should expire.

**Comment by BrandonPotter** [comment]
This is normally how two-factor auth codes work.

If you want to keep track of codes used to invalidate them, you can still do that within your application layer, but this library is intended to be stateless.

**Comment by sanasz91mdev** [comment]
any reference? Because gmail does expire this google authenticator code once used for validation.

**Comment by sanasz91mdev** [comment]
> This is normally how two-factor auth codes work.
> 
> If you want to keep track of codes used to invalidate them, you can still do that within your application layer, but this library is intended to be stateless.

any reference? Because gmail does expire this google authenticator code once used for validation.

**Comment by sekulicb** [comment]
Hi. I can confirm that keys are never invalidated. This is not desired behavior. What would be the point of 30 seconds window then ?

**Comment by BrandonPotter** [comment]
This library is stateless - it does not come with a database and does not have any context into what user it’s validating.

If you want to make this stateful, that is - you need to keep track of which users have used which codes, that is the responsibility of your application code to do that (for example, a table with UserID, Timestamp, and TwoFactorCode that you can query against to see if a user has used the same code in the last 5 minutes), keeping in mind that codes can be reused eventually.
