### ISSUE TITLE
Will this support MS Authenticator and Authy

### ISSUE THREAD

**Issue by vijayaram-b** [BrandonPotter/GoogleAuthenticator#228]
Hi,

We are trying to use this in one of our projects, where MFA is mandated, we wanted to check the feasibility of using this library.

Will the library supports only Google Authenticator or generally any authenticator app(we are interested in Microsoft and Authy)

Please check and advise

**Comment by ahwm** [comment]
I have successfully generated working codes on Microsoft Authenticator, Authy, Google Authenticator, 2FAS, LastPass Authenticator and a previous version of Authenticator Plus (now seems to be defunct).

Note: Some of these (notably Microsoft Authenticator and Authy) will only work with the default algorithm (HMACSHA1) and will not work with HMACSHA256 or HMACSHA512, even though the RFC standard supports those.

**Comment by vijayaram-b** [comment]
Thank you @ahwm, will check with that

**Comment by vijayaram-b** [comment]
Hi @ahwm 
I have been trying this in WinTest app, after changing this to default algorithm (HMACSHA1), will it have any security implication going forward if I am not using other algorithms?

**Comment by flytzen** [comment]
No, HMACSHA1 is the default used by most authenticator apps.
