### ISSUE TITLE
TwoFactorAuthenticator: error when validating keys with a leading zero

### ISSUE THREAD

**Issue by iacepero** [BrandonPotter/GoogleAuthenticator#232]
Hello, I have a problem with the "TwoFactorAuthenticator".
It turns out that key generation applications such as Microsoft Authenticator generate keys with numeric digits that may contain a 0 at the beginning of the chain.

The PasswordToken.FromPassCode method only accepts values ​​of the "INT" type, so when trying to validate a code with a leading zero, it fails.

Can this problem be solved?

Thanks in advance. Isi

**Comment by ahwm** [comment]
Can you give some context on how you're doing the 2FA validation? `PasswordToken` isn't a class part of this library.

**Comment by iacepero** [comment]
> Can you give some context on how you're doing the 2FA validation? `PasswordToken` isn't a class in this library.
Hi, I got here from this link:
https://github.com/tobster-de/TwoFactorAuthenticator

**Comment by ahwm** [comment]
You will need to address that in that repository then. Or switch to this library.
