### ISSUE TITLE
TwoFacAuth.ValidateTwoFactorPIN every time retuns false

### ISSUE THREAD

**Issue by dborovsky** [BrandonPotter/GoogleAuthenticator#25]
`bool isValid = TwoFacAuth.ValidateTwoFactorPIN(UserUniqueKey, token);`

I have tried above code but, the code always returning false even if unique key and token is correct.

**Comment by ahwm** [comment]
I have this code and it works perfectly:

```csharp
TwoFactorAuthenticator tfa = new TwoFactorAuthenticator();
if (tfa.ValidateTwoFactorPIN(secretKey, userInputCode))
	tfaValid = true;
```

Included in the solution is a WinForms project that can be used for testing as well. Are there any other details that might help figure out where the problem is?

**Comment by dborovsky** [comment]
Strange...

I have created demo application

I have following code:

```
private const string key = "qazqaz12345"; //You can add your own Key
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModel login)
        {
            string message = "";
            bool status = false;
            //check UserName and password form our database here
            if (login.UserName == "Admin" && login.Password == "12345") // Admin as user name and 12345 as Password
            {
                status = true;
                message = "Two Factor Authentication Verification";
                Session["UserName"] = login.UserName;
                //Two Factor Authentication Setup
                TwoFactorAuthenticator TwoFacAuth = new TwoFactorAuthenticator();
                **string UserUniqueKey = (login.UserName + key);**
                Session["UserUniqueKey"] = UserUniqueKey;
                var setupInfo = TwoFacAuth.GenerateSetupCode("Dot Net Detail", login.UserName, UserUniqueKey, 300, 300);
                ViewBag.BarcodeImageUrl = setupInfo.QrCodeSetupImageUrl;
                ViewBag.SetupCode = setupInfo.ManualEntryKey;
            }
            else
            {
                message = "Please Enter the Valid Credential!";
            }
            ViewBag.Message = message;
            ViewBag.Status = status;
            return View();
        }
```
I get code in Google Auth mobile app. 

And use this code  to verify:

```
public ActionResult TwoFactorAuthenticate()
        {
            var token = Request["CodeDigit"];
            TwoFactorAuthenticator TwoFacAuth = new TwoFactorAuthenticator();
            string UserUniqueKey = Session["UserUniqueKey"].ToString();
            bool isValid = TwoFacAuth.ValidateTwoFactorPIN(UserUniqueKey, token);
            if (isValid)
            {
                Session["IsValidTwoFactorAuthentication"] = true;
                return RedirectToAction("UserProfile", "Home");
            }
            return RedirectToAction("Login", "Home");
        }
```
But return false. 

I checked **var token = Request["CodeDigit"]** is correct. Maybe I do something incorrect?

**Comment by ahwm** [comment]
@dborovsky I'm not sure what's going on with your system. I tried your code in a sample application and it validated correctly every time.

Here's what I did -

1. Created new MVC Web Application (.NET Framework)
2. Installed GoogleAuthenticator nuget package (1.2.1)
3. Added code:

Index.cshtml:
```razor
<div class="row">
    <img src="@ViewBag.BarcodeImageUrl" /><br />
    @ViewBag.SetupCode
</div>

<div class="row">
    @using(Html.BeginForm("Verify2FA", "Home", FormMethod.Post))
    {
        <input type="text" name="CodeDigit" /><br />
        <button class="btn btn-primary">Verify</button>
    }
    @if (ViewBag.IsValid != null)
    {
        if ((bool)ViewBag.IsValid)
        {
            <span style="color:green;">Valid</span>
        }
        else
        {
            <span style="color:red;">Invalid</span>
        }
    }
</div>
```

HomeController.cs:

```csharp
private const string key = "qazqaz12345";
public ActionResult Index()
{
    Session["UserName"] = "Admin";
    TwoFactorAuthenticator TwoFA = new TwoFactorAuthenticator();
    string UserUniqueKey = ("Admin" + key);
    Session["UserUniqueKey"] = UserUniqueKey;
    var info = TwoFA.GenerateSetupCode("Dot Net Detail", "Admin", UserUniqueKey, 300, 300);
    ViewBag.BarcodeImageUrl = info.QrCodeSetupImageUrl;
    ViewBag.SetupCode = info.ManualEntryKey;
    return View();
}

[HttpPost]
public ActionResult Verify2FA()
{
    var token = Request["CodeDigit"];
    TwoFactorAuthenticator TwoFacAuth = new TwoFactorAuthenticator();
    string UserUniqueKey = Session["UserUniqueKey"].ToString();
    ViewBag.IsValid = TwoFacAuth.ValidateTwoFactorPIN(UserUniqueKey, token, TimeSpan.FromSeconds(60));

    return View("Index");
}
```

This gave me the green "Valid" every time. I'm not sure what's different for you. The only thing I could see being a problem is if your system time is off.

**Comment by dborovsky** [comment]
which version of .net framework do you use?

**Comment by dborovsky** [comment]
I found error. If Application is running on my localhost(windows 7) return true. But if I run on remotre windows server 2012 return every time false. What could be the reason?

**Comment by dborovsky** [comment]
I checked your source code and found error. You use local time to generate hash codes. But localtime on remote server  is different. I changed local time on server to my local time and now method retuns true.

**Comment by ahwm** [comment]
If you mean here:

```csharp
        private long GetCurrentCounter()
        {
            return GetCurrentCounter(DateTime.UtcNow, _epoch, 30);
        }

        private long GetCurrentCounter(DateTime now, DateTime epoch, int timeStep)
        {
            return (long)(now - epoch).TotalSeconds / timeStep;
        }
```

Notice it's using **`DateTime.UtcNow`** - that's not "local" time. UTC time right now is 3:08pm. UTC right now anywhere in the world is going to be 3:08pm. That's why UTC is used. In my example, I'm not passing in any specific time. Just a `TimeSpan` object indicating how long a code should be valid.

**Comment by dborovsky** [comment]
yes. I think  You are right. Thanks for your support.

**Comment by ahwm** [comment]
Happy to help out. Were you able to figure out what was going on?

**Comment by dfibuch** [comment]
I've just been playing around with the example from Dot Net Detail and had the problem where it would validate an old token, which I don't think it should. I read through the convo here and it's the timeout on the `ValidateTwoFactorPIN` method that I didn't set, so I changed it to:

`TwoFacAuth.ValidateTwoFactorPIN(UserUniqueKey, token, TimeSpan.FromSeconds(30));`

And now it only validates the active token.

**Comment by ahwm** [comment]
@dfibuch Yes, I'm not sure why the default is 5 minutes where the RFC only really allows 60 (to allow the expiring code to work). But I'm glad you were able to figure out the issue!
