### ISSUE TITLE
Support for .Net Framework 4.5.1

### ISSUE THREAD

**Issue by flytzen** [BrandonPotter/GoogleAuthenticator#28]
If easy - for backwards compatibility

**Comment by ahwm** [comment]
I believe the new NET Standard version is multi-targeted for .NET 4.5 so should work on 4.5.1 out-of-the-box. Worth checking.

**Comment by flytzen** [comment]
@ahwm Doh! You are spot on - for some reason I thought you were targeting 4.6.2. Closing :)

**Comment by ahwm** [comment]
I think I did at first but then moved it back to 4.5. :)
