### ISSUE TITLE
Support develop branch / auto publish of pre-release

### ISSUE THREAD

**Issue by flytzen** [BrandonPotter/GoogleAuthenticator#30]
Suggestion: Add a `develop` branch and some version numbering so you can easily merge PRs into develop and have them automatically published as pre-release versions on Nuget.

I can set it up easily enough - if you want it?

@BrandonPotter @ahwm

**Comment by ahwm** [comment]
I'm down with that. I'm not sure if there will be enough development to really support that, though.

**Comment by flytzen** [comment]
Fair point, closing.

**Comment by ahwm** [comment]
Just something I thought of - Would it make sense to base full releases to NuGet on tags instead of just `master`?

I guess we would otherwise just have a `2.0` branch, huh? And then just merge that to `master` when a release is ready?

Just wanted to clarify.

**Comment by flytzen** [comment]
I think tags is probably the easiest, especially as we already have all the 2.0 stuff in `master` anyway. 
I always use GitFlow in my own stuff but I agree that it's overkill here.

**Comment by flytzen** [comment]
I've added a simple thing in AzDO to tag master when deployed to Nuget. It doesn't tag it with the actual package number (at least I don't think so) but it should at least show that it as pushed and we should be able to then find the release in AzDO to track it back.
