### ISSUE TITLE
Add Release pipeline for the Nuget Package

### ISSUE THREAD

**Issue by flytzen** [BrandonPotter/GoogleAuthenticator#36]
Hi @BrandonPotter,

Azure is now building the nuget package. To make it easier to publish to Nuget, I suggest setting up a release pipeline with approval; every time a commit to `master` succeeds, you will be asked if you want to deploy that package to NuGet.
In order to finish setting up that release pipeline, I need you to set up a "Service Connection". First, you need to create an API key in Nuget, then add it to the Azure DevOps pipeline:

<img width="973" alt="NugetConnectionOne" src="https://user-images.githubusercontent.com/1202983/71542861-a0882700-2963-11ea-8b83-588b9aed931a.png">
<img width="572" alt="NugetConnectionTwo" src="https://user-images.githubusercontent.com/1202983/71542864-a41bae00-2963-11ea-8066-6af3315299f7.png">
<img width="589" alt="NugetConnectionThree" src="https://user-images.githubusercontent.com/1202983/71542865-a67e0800-2963-11ea-847e-8b2ca612fe5c.png">

**Comment by BrandonPotter** [comment]
This should be in place now

**Comment by flytzen** [comment]
@BrandonPotter I can't see it unfortunately. Maybe a permissions issue.
Do you want to screenshare on it at some point - may be faster (especially as there is something else I am also not allowed to do on AzDO :)).
You can ping me on twitter @flytzen if that's easier :)

**Comment by BrandonPotter** [comment]
There are security settings on the service connection - just changed them - can you see it now?

**Comment by flytzen** [comment]
@BrandonPotter yes, all working now.
I've created a Release pipeline. If you go into AzDO -> Releases, you can click "Create release" and that should push to Nuget.
I've added an approval step, meaning AzDO will require you to approve pushing to NuGet.

There is more automation we *could* do, but it's probably not worth doing more :)
