### ISSUE TITLE
QR code generated uses deprecated API

### ISSUE THREAD

**Issue by stephenlawuk** [BrandonPotter/GoogleAuthenticator#4]
`string url = String.Format("{0}://chart.googleapis.com/chart?cht=qr&chs={1}x{2}&chl={3}", protocol, qrCodeWidth, qrCodeHeight, provisionUrl);
`

"Warning: This API is deprecated."
https://developers.google.com/chart/infographics/docs/qr_codes

You should probably move away from using the Google QR code generator as it is a deprecated API that could be removed at any time. 

This blog also highlights the risk of using externally generated QR codes for Google authenticator as the QR code contains cryptography secrets. It also suggests that QR codes can be generated locally using javascript as a solution.
http://blog.geuer-pollmann.de/blog/2014/12/15/generating-qr-codes-in-html/

Changing your QR generation so that it is locally generated would increase security and also allow for local intranet usage where an internet connection may not be available. If there is no internet connection you would currently not be able to generate a QR code.

Edit: I'm currently using this pure C# QR renderer https://github.com/codebude/QRCoder

**Comment by FahdSaif** [comment]
Hi, quite informative. What is the alternative to use with FPDF library which makes PDF files

**Comment by ahwm** [comment]
I added a pull request that uses QRCoder as the QR generator as I ran into the same issue.

**Comment by ahwm** [comment]
I'm going to close this since there is a version where this is possible.
