### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by flytzen** [BrandonPotter/GoogleAuthenticator#42]
Are we ready to release 2.0?
Should we push the 2.0.0-beta1 package and let it sit there for a bit to let people find issues?
Are we aware of anything we need to do before releasing 2.0?

**Comment by BrandonPotter** [comment]
As long as its a major version increment I have no issues pushing it... that way folks with a minor version auto-upgrade nuget config won’t be affected unless they manually upgrade, but new apps can start using 2.0. Feel good?

**Comment by ahwm** [comment]
I'm good with that. I've been using most of the 2.0 changes in production on my own for a while, anyway. I just created a pull request to change it to 2.0 instead of 2.0.0-beta1.

**Comment by BrandonPotter** [comment]
Looks like a pipeline warning on nuget publish -- 

```
2020-01-02T17:01:53.5203527Z ##[warning]No packages matched the search pattern.
```

**Comment by flytzen** [comment]
Bugger. I'll fix. Sorry.

**Comment by BrandonPotter** [comment]
No worries! Getting close...

**Comment by flytzen** [comment]
@BrandonPotter Okay, fixed that. Turns out the default path to the build artifacts directory was not correct :(
But, now getting `System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.)`.
It's possible the API key does not have the correct permissions?

**Comment by ahwm** [comment]
Yeah, you do have to grant permission to specific packages.

**Comment by BrandonPotter** [comment]
Checking - that API key was specifically granted to the GoogleAuthenticator package... more shortly..

**Comment by BrandonPotter** [comment]
Permissions look good to `Push new packages and package versions` for `GoogleAuthenticator`.

I'll regenerate the API key just in case I missed the copy/paste or something?

**Comment by BrandonPotter** [comment]
Regenerated, service connection updated - try again?

**Comment by ahwm** [comment]
`System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).`

**Comment by BrandonPotter** [comment]
Where can I download the .nupkg generated? Want to crack it open and verify the package name etc is correct...

**Comment by ahwm** [comment]
https://dev.azure.com/brandon-potter/_apis/resources/Containers/4159203?itemPath=NugetPackage%2FGoogle.Authenticator.2.0.0.nupkg

**Comment by flytzen** [comment]
AH! It's become "Google.Authenticator" somewhere along the line.

**Comment by flytzen** [comment]
Lemme do a quick PR

**Comment by ahwm** [comment]
Ooh. That makes sense. The change to netstandard would have removed the need for a nuspec and defaulted the package id to the project name.

**Comment by flytzen** [comment]
Wooop! Just waiting for the Nuget indexer now, I think.

**Comment by BrandonPotter** [comment]
Success!

**Comment by ahwm** [comment]
Nuget is showing it on their side now, too. Just has to be indexed.

**Comment by BrandonPotter** [comment]
Looking like it's live, thank you both!!!
