### ISSUE TITLE
SetupCode has redundant property

### ISSUE THREAD

**Issue by dfibuch** [BrandonPotter/GoogleAuthenticator#45]
Looks like as of V2 the `AccountSecretKey` is no longer used or populated so should be removed.

**Comment by ahwm** [comment]
You are correct. That was an apparent oversight. The secret key is being passed in by the application so there's no need for the library to return it.

Neither the Windows Form test nor the web test projects were using that, either.

**Comment by dfibuch** [comment]
Yeah I noticed it because I was actually generating the secret in a helper method and then passing it back with my `SetupCode` so I can store it, but since the upgrade it was `null`. I can make a PR to remove it if you want.

**Comment by flytzen** [comment]
@BrandonPotter Would you be able to approve the deploy to get this into Nuget (it's 2.0.1)?

**Comment by BrandonPotter** [comment]
Done!
