### ISSUE TITLE
Image size 19500 x 19500?

### ISSUE THREAD

**Issue by gerwinreuling** [BrandonPotter/GoogleAuthenticator#47]
When setting QRPixelsPerModule to 300 generates a image of 19500 x 19500
looks like a bug?
![authfail](https://user-images.githubusercontent.com/17931686/72360049-af0a6880-36ef-11ea-9441-344013ee920b.jpg)

**Comment by ahwm** [comment]
This actually isn't a bug. In this instance, the QRCoder package is asking for the number of pixels per module. A module is one square in the QR code. So a setting of 2 generates a QR code approximately 120x120 pixels.

Using the WebSample project, I set the QRPixelsPerModule to 3 and ended up with an image 171x171.

![image](https://user-images.githubusercontent.com/20478373/72361340-8ca42b00-36ae-11ea-9936-e9c4aa61f3c0.png)

**Comment by gerwinreuling** [comment]
Ok, thanx for the info, didn't know that module was one square in the QR Code.  My mistake. Thanks for the info.
