### ISSUE TITLE
Make ValidateTwoFactorPIN overload that accepts byte[]

### ISSUE THREAD

**Issue by Dimo99** [BrandonPotter/GoogleAuthenticator#48]
Currently ValidateTwoFactorPIN only accepts UTF8 encoded string, which in my opinion is not correct as not every byte sequence is valid UTF8 string. And for the setup there is overload that accepts byte[]. So the same should be for ValidateTwoFactorPIN.

**Comment by flytzen** [comment]
I see your point; the setup allows you to pass in your *account secret* as a byte array as well as a string.

Whereas in the validate flow, you can only pass in the secret as a string and we assume that this string is a valid UTF8 string. In other words, the library makes an explicit assumption that you are storing your account secrets as strings.

Technically it would be more correct to allow the account secret to also be passed in as a byte array. Internally the secret is immediately converted to a byte array anyway. 

The question is whether there is an actual use case for it - i.e. are you actually wanting to store the secret as a byte array or are you just making an observation? 
Either way, if you are able to provide a PR with the overloads it would be great; You should probably change the existing string-based methods to call the new byte[]-based methods. It would ideally also need some unit tests for the existing string-based methods that pass both before and after the refactor.

@ahwm - any thoughts?

**Comment by ahwm** [comment]
Sounds good to me. I agree with making the existing string methods call the new byte[] method(s).

Providing a PR is definitely a good way to get it done faster. :)

**Comment by flytzen** [comment]
Open PR: #53

**Comment by Hiryus** [comment]
Hello,

Could you release this PR please ? :)

To answer @flytzen question, here is my use case:
I used `GenerateSetupCode()` with byte array since I don't want to generate a QRCode and the method only accepts bytes array with the `generateQrCode` parameter. Also, most cryptographic random generators output bytes arrays and not UTF8 strings, including the one I use.
However, I now notice that `ValidateTwoFactorPIN()` does not accept bytes array, but only a string.

I'm currently converting my key from bytes to an UTF8 string for `ValidateTwoFactorPIN()` but it is hacky since random bytes are not printable at all.

**Comment by flytzen** [comment]
@Hiryus yep, we're on it, releasing in the next day or so 👍

**Comment by Hiryus** [comment]
Just in case someone stumble on the same issue:
Passing `Encoding.UTF8.GetString(bytes_array_key)` to `ValidateTwoFactorPIN()` will not work if `bytes_array_key` contains invalid UTF8 bytes / characters, despite the library converting it back to bytes immediately.

You can test it with this little snippet:
```
byte[] initial = ...
string key = Encoding.UTF8.GetString(initial);
byte[] final = Encoding.UTF8.GetBytes(key );
// initial != final
```

What you can do, however, is encode it in base32 and pass the result to `ValidateTwoFactorPIN()`.

**Comment by ahwm** [comment]
Hey @Hiryus were you seeing this behavior with the new 2.4 release? This version has some functionality fixes in this area, but if it’s still not working correctly then we’ll dig in a bit more.

**Comment by flytzen** [comment]
@Hiryus Am I understanding you correctly that you are saying that *if* you choose to store the secret as a string, you will sometimes have trouble because of the nature of UTF8?
But if you consistently use a byte array then this library works correctly?

**Comment by Hiryus** [comment]
> Hey @Hiryus were you seeing this behavior with the new 2.4 release? This version has some functionality fixes in this area, but if it’s still not working correctly then we’ll dig in a bit more.

Sorry for the delayed answer - I have some problem with github notification it seems.

I ended up converted the bytes array into base32 string and using this base32 string everywhere (in my database and in calls to the library). This is actually simpler.

However, the changes seemed right to me when you published them.

**Comment by flytzen** [comment]
@Hiryus Thank you for clarifying 👍
