### ISSUE TITLE
Backup codes

### ISSUE THREAD

**Issue by cmcclellan01** [BrandonPotter/GoogleAuthenticator#49]
Any way to issue backup codes with this?

**Comment by ahwm** [comment]
I believe that's really outside the scope of this library. Unless @flytzen or @BrandonPotter disagree. You could just use a random number generator to create however many you want:

https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rngcryptoserviceprovider?view=netframework-4.8

**Comment by flytzen** [comment]
@cmcclellan01 With backup codes, do you mean a recovery code, i.e. a different way to log in in case you lose your authentication app setup? If so, no that is explicitly not what this library is about, sorry.
