### ISSUE TITLE
HI,class TwoFactorAuthenticator's private method UrlEncode(string value) not Not compatible Chinese

### ISSUE THREAD

**Issue by coolbytebyte** [BrandonPotter/GoogleAuthenticator#50]
the method UrlEncode(string value) in class TwoFactorAuthenticator not Not compatible Chinese,it can not Encode Chinese rightly,so when i use GA app to scan qrcode,it doesn't show a issure name or account name.i created a class that exdents class TwoFactorAuthenticator  and change the method UrlEncode(string value) to call method WebUtility.UrlEncode(value),now it work with chinese.

**Comment by ahwm** [comment]
That sounds great! Can you provide a copy or do a pull request?

**Comment by coolbytebyte** [comment]
<pre style="color:#000000;background:#ffffff;">        private class MyTwoFactorAuthenticator <span style="color:#800080; ">:</span> TwoFactorAuthenticator
        <span style="color:#800080; ">{</span>
            <span style="color:#3f5fbf; ">/// &lt;summary&gt;</span>
            <span style="color:#3f5fbf; ">/// Generate a setup code for a Google Authenticator user to scan</span>
            <span style="color:#3f5fbf; ">/// &lt;/summary&gt;</span>
            <span style="color:#3f5fbf; ">/// &lt;param name="issuer"&gt;Issuer ID (the name of the system, i.e. 'MyApp'), can be omitted but not recommended https://github.com/google/google-authenticator/wiki/Key-Uri-Format &lt;/param&gt;</span>
            <span style="color:#3f5fbf; ">/// &lt;param name="accountTitleNoSpaces"&gt;Account Title (no spaces)&lt;/param&gt;</span>
            <span style="color:#3f5fbf; ">/// &lt;param name="accountSecretKey"&gt;Account Secret Key&lt;/param&gt;</span>
            <span style="color:#3f5fbf; ">/// &lt;param name="secretIsBase32"&gt;Flag saying if accountSecretKey is in Base32 format or original secret&lt;/param&gt;</span>
            <span style="color:#3f5fbf; ">/// &lt;param name="QRPixelsPerModule"&gt;Number of pixels per QR Module (2 pixels give ~ 100x100px QRCode)&lt;/param&gt;</span>
            <span style="color:#3f5fbf; ">/// &lt;returns&gt;SetupCode object&lt;/returns&gt;</span>
            public new SetupCode GenerateSetupCode<span style="color:#808030; ">(</span>string issuer<span style="color:#808030; ">,</span> string accountTitleNoSpaces<span style="color:#808030; ">,</span> string accountSecretKey<span style="color:#808030; ">,</span>
                bool secretIsBase32<span style="color:#808030; ">,</span> <span style="color:#800000; font-weight:bold; ">int</span> QRPixelsPerModule<span style="color:#808030; ">)</span>
            <span style="color:#800080; ">{</span>
                byte<span style="color:#808030; ">[</span><span style="color:#808030; ">]</span> key <span style="color:#808030; ">=</span> secretIsBase32
                    <span style="color:#800080; ">?</span> Base32Encoding<span style="color:#808030; ">.</span>ToBytes<span style="color:#808030; ">(</span>accountSecretKey<span style="color:#808030; ">)</span>
                    <span style="color:#800080; ">:</span> Encoding<span style="color:#808030; ">.</span>UTF8<span style="color:#808030; ">.</span>GetBytes<span style="color:#808030; ">(</span>accountSecretKey<span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
                <span style="color:#800000; font-weight:bold; ">return</span> GenerateSetupCode<span style="color:#808030; ">(</span>issuer<span style="color:#808030; ">,</span> accountTitleNoSpaces<span style="color:#808030; ">,</span> key<span style="color:#808030; ">,</span> QRPixelsPerModule<span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
            <span style="color:#800080; ">}</span>

            <span style="color:#3f5fbf; ">/// &lt;summary&gt;</span>
            <span style="color:#3f5fbf; ">/// Generate a setup code for a Google Authenticator user to scan</span>
            <span style="color:#3f5fbf; ">/// &lt;/summary&gt;</span>
            <span style="color:#3f5fbf; ">/// &lt;param name="issuer"&gt;Issuer ID (the name of the system, i.e. 'MyApp'), can be omitted but not recommended https://github.com/google/google-authenticator/wiki/Key-Uri-Format &lt;/param&gt;</span>
            <span style="color:#3f5fbf; ">/// &lt;param name="accountTitleNoSpaces"&gt;Account Title (no spaces)&lt;/param&gt;</span>
            <span style="color:#3f5fbf; ">/// &lt;param name="accountSecretKey"&gt;Account Secret Key as byte[]&lt;/param&gt;</span>
            <span style="color:#3f5fbf; ">/// &lt;param name="QRPixelsPerModule"&gt;Number of pixels per QR Module (2 = ~120x120px QRCode)&lt;/param&gt;</span>
            <span style="color:#3f5fbf; ">/// &lt;returns&gt;SetupCode object&lt;/returns&gt;</span>
            public new SetupCode GenerateSetupCode<span style="color:#808030; ">(</span>string issuer<span style="color:#808030; ">,</span> string accountTitleNoSpaces<span style="color:#808030; ">,</span> byte<span style="color:#808030; ">[</span><span style="color:#808030; ">]</span> accountSecretKey<span style="color:#808030; ">,</span>
                <span style="color:#800000; font-weight:bold; ">int</span> QRPixelsPerModule<span style="color:#808030; ">,</span> bool generateQrCode <span style="color:#808030; ">=</span> true<span style="color:#808030; ">)</span>
            <span style="color:#800080; ">{</span>
                <span style="color:#800000; font-weight:bold; ">if</span> <span style="color:#808030; ">(</span><span style="color:#603000; ">String</span><span style="color:#808030; ">.</span>IsNullOrWhiteSpace<span style="color:#808030; ">(</span>accountTitleNoSpaces<span style="color:#808030; ">)</span><span style="color:#808030; ">)</span>
                <span style="color:#800080; ">{</span>
                    throw new NullReferenceException<span style="color:#808030; ">(</span><span style="color:#800000; ">"</span><span style="color:#0000e6; ">Account Title is null</span><span style="color:#800000; ">"</span><span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
                <span style="color:#800080; ">}</span>

                accountTitleNoSpaces <span style="color:#808030; ">=</span> RemoveWhitespace<span style="color:#808030; ">(</span>Uri<span style="color:#808030; ">.</span>EscapeUriString<span style="color:#808030; ">(</span>accountTitleNoSpaces<span style="color:#808030; ">)</span><span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
                string encodedSecretKey <span style="color:#808030; ">=</span> Base32Encoding<span style="color:#808030; ">.</span>ToString<span style="color:#808030; ">(</span>accountSecretKey<span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
                string provisionUrl<span style="color:#800080; ">;</span>
                <span style="color:#800000; font-weight:bold; ">if</span> <span style="color:#808030; ">(</span><span style="color:#603000; ">String</span><span style="color:#808030; ">.</span>IsNullOrWhiteSpace<span style="color:#808030; ">(</span>issuer<span style="color:#808030; ">)</span><span style="color:#808030; ">)</span>
                <span style="color:#800080; ">{</span>
                    provisionUrl <span style="color:#808030; ">=</span> <span style="color:#603000; ">String</span><span style="color:#808030; ">.</span>Format<span style="color:#808030; ">(</span><span style="color:#800000; ">"</span><span style="color:#0000e6; ">otpauth://totp/{0}?secret={1}</span><span style="color:#800000; ">"</span><span style="color:#808030; ">,</span> accountTitleNoSpaces<span style="color:#808030; ">,</span>
                        encodedSecretKey<span style="color:#808030; ">.</span>Trim<span style="color:#808030; ">(</span><span style="color:#0000e6; ">'='</span><span style="color:#808030; ">)</span><span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
                <span style="color:#800080; ">}</span>
                <span style="color:#800000; font-weight:bold; ">else</span>
                <span style="color:#800080; ">{</span>
                    <span style="color:#696969; ">//  </span><span style="color:#5555dd; ">https://github.com/google/google-authenticator/wiki/Conflicting-Accounts</span>
                    <span style="color:#696969; ">// Added additional prefix to account otpauth://totp/Company:</span><span style="color:#7144c4; ">joe_example@gmail.com</span><span style="color:#696969; "> for backwards compatibility</span>
                    provisionUrl <span style="color:#808030; ">=</span> <span style="color:#603000; ">String</span><span style="color:#808030; ">.</span>Format<span style="color:#808030; ">(</span><span style="color:#800000; ">"</span><span style="color:#0000e6; ">otpauth://totp/{2}:{0}?secret={1}&amp;issuer={2}</span><span style="color:#800000; ">"</span><span style="color:#808030; ">,</span> accountTitleNoSpaces<span style="color:#808030; ">,</span>
                        encodedSecretKey<span style="color:#808030; ">.</span>Trim<span style="color:#808030; ">(</span><span style="color:#0000e6; ">'='</span><span style="color:#808030; ">)</span><span style="color:#808030; ">,</span> UrlEncode<span style="color:#808030; ">(</span>issuer<span style="color:#808030; ">)</span><span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
                <span style="color:#800080; ">}</span>

                string qrCodeUrl <span style="color:#808030; ">=</span> string<span style="color:#808030; ">.</span>Empty<span style="color:#800080; ">;</span>
                <span style="color:#800000; font-weight:bold; ">if</span> <span style="color:#808030; ">(</span>generateQrCode<span style="color:#808030; ">)</span>
                <span style="color:#800080; ">{</span>
                    <span style="color:#800000; font-weight:bold; ">using</span> <span style="color:#808030; ">(</span>QRCodeGenerator qrGenerator <span style="color:#808030; ">=</span> new QRCodeGenerator<span style="color:#808030; ">(</span><span style="color:#808030; ">)</span><span style="color:#808030; ">)</span>
                    <span style="color:#800000; font-weight:bold; ">using</span> <span style="color:#808030; ">(</span>QRCodeData qrCodeData <span style="color:#808030; ">=</span> qrGenerator<span style="color:#808030; ">.</span>CreateQrCode<span style="color:#808030; ">(</span>provisionUrl<span style="color:#808030; ">,</span> QRCodeGenerator<span style="color:#808030; ">.</span>ECCLevel<span style="color:#808030; ">.</span>Q<span style="color:#808030; ">)</span><span style="color:#808030; ">)</span>
                    <span style="color:#800000; font-weight:bold; ">using</span> <span style="color:#808030; ">(</span>QRCode qrCode <span style="color:#808030; ">=</span> new QRCode<span style="color:#808030; ">(</span>qrCodeData<span style="color:#808030; ">)</span><span style="color:#808030; ">)</span>
                    <span style="color:#800000; font-weight:bold; ">using</span> <span style="color:#808030; ">(</span>Bitmap qrCodeImage <span style="color:#808030; ">=</span> qrCode<span style="color:#808030; ">.</span>GetGraphic<span style="color:#808030; ">(</span>QRPixelsPerModule<span style="color:#808030; ">)</span><span style="color:#808030; ">)</span>
                    <span style="color:#800000; font-weight:bold; ">using</span> <span style="color:#808030; ">(</span>MemoryStream ms <span style="color:#808030; ">=</span> new MemoryStream<span style="color:#808030; ">(</span><span style="color:#808030; ">)</span><span style="color:#808030; ">)</span>
                    <span style="color:#800080; ">{</span>
                        qrCodeImage<span style="color:#808030; ">.</span>Save<span style="color:#808030; ">(</span>ms<span style="color:#808030; ">,</span> System<span style="color:#808030; ">.</span>Drawing<span style="color:#808030; ">.</span>Imaging<span style="color:#808030; ">.</span>ImageFormat<span style="color:#808030; ">.</span>Png<span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>

                        qrCodeUrl <span style="color:#808030; ">=</span> $<span style="color:#800000; ">"</span><span style="color:#0000e6; ">data:image/png;base64,{Convert.ToBase64String(ms.ToArray())}</span><span style="color:#800000; ">"</span><span style="color:#800080; ">;</span>
                    <span style="color:#800080; ">}</span>
                <span style="color:#800080; ">}</span>

                <span style="color:#800000; font-weight:bold; ">return</span> new SetupCode<span style="color:#808030; ">(</span>accountTitleNoSpaces<span style="color:#808030; ">,</span> encodedSecretKey<span style="color:#808030; ">.</span>Trim<span style="color:#808030; ">(</span><span style="color:#0000e6; ">'='</span><span style="color:#808030; ">)</span><span style="color:#808030; ">,</span> qrCodeUrl<span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
            <span style="color:#800080; ">}</span>

            private <span style="color:#800000; font-weight:bold; ">static</span> string RemoveWhitespace<span style="color:#808030; ">(</span>string str<span style="color:#808030; ">)</span>
            <span style="color:#800080; ">{</span>
                <span style="color:#800000; font-weight:bold; ">return</span> new string<span style="color:#808030; ">(</span>str<span style="color:#808030; ">.</span>Where<span style="color:#808030; ">(</span>c <span style="color:#808030; ">=</span><span style="color:#808030; ">&gt;</span> <span style="color:#808030; ">!</span>Char<span style="color:#808030; ">.</span>IsWhiteSpace<span style="color:#808030; ">(</span>c<span style="color:#808030; ">)</span><span style="color:#808030; ">)</span><span style="color:#808030; ">.</span>ToArray<span style="color:#808030; ">(</span><span style="color:#808030; ">)</span><span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
            <span style="color:#800080; ">}</span>


            private string UrlEncode<span style="color:#808030; ">(</span>string value<span style="color:#808030; ">)</span>
            <span style="color:#800080; ">{</span>
                <span style="color:#696969; ">//Solve the problem of invalid Chinese escape</span>
                <span style="color:#800000; font-weight:bold; ">return</span> WebUtility<span style="color:#808030; ">.</span>UrlEncode<span style="color:#808030; ">(</span>value<span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
            <span style="color:#800080; ">}</span>
        <span style="color:#800080; ">}</span>
</pre>

**Comment by AmmonLin** [comment]
@flytzen 
Use `Uri.EscapeDataString` instead of `Uri.EscapeUriString`, `UrlEncode(issuer)` will solve this issue.
For more information about uri escape, see [stackoverflow answer](https://stackoverflow.com/questions/4396598/whats-the-difference-between-escapeuristring-and-escapedatastring/34189188#34189188).

**Comment by flytzen** [comment]
@ahwm FYI:  I did some work on this over the weekend but didn't finish it. I am trying to add some tests to the QR code but it's proving challenging. If we are in a rush we can skip the tests, but otherwise, I'd like to get them in there ;)

**Comment by ahwm** [comment]
I don't think we're in a rush.
