### ISSUE TITLE
Device registering

### ISSUE THREAD

**Issue by njm-Onefile-SRE** [BrandonPotter/GoogleAuthenticator#52]
There does not appear to be any included feature to link a device with an account.
Is that smoething that needs to be done separately?

If so, it may be worth pointing that out in the Readme, together with a small amoount of info as to what a recommended way might be to achieve that, or links to useful info about it.

As it stands, there is a risk of someone using this, thinking it is a full 2fa solution, as opposed to a 2fa component.

Regards.

**Comment by ahwm** [comment]
I'm not sure I understand what you mean. Are you talking about like a USB security key? Yeah, this library only works with software-based TOTP solutions such as (not an exhaustive list):

* Google Authenticator
* Microsoft Authenticator
* LastPass Authenticator
* Authy
* Authenticator Plus

Registering a "device" using one of these apps typically includes generating a secret key, getting a setup code and QR code image for the user to either enter or scan in their app of choice, and then verifying one or two (your choice, but should be at least one) successive codes. You store the secret and use that to verify codes when prompting the user.

See the [Wiki](https://github.com/BrandonPotter/GoogleAuthenticator/wiki) for code sample. There are also some examples in the solution for WebForms and WinForms.

**Comment by njm-Onefile-SRE** [comment]
Hi Adam.
That makes sense, thanks.
