### ISSUE TITLE
Memory Spike getting QR Code

### ISSUE THREAD

**Issue by eramosr16** [BrandonPotter/GoogleAuthenticator#55]
I came across this issue creating the QR Code image inside a docker container with limited resources in RAM, the container starts with 140mb of ram and once I call the endpoint to create the image it goes up to 1.7 GB of Ram just after calling the method. Is there a way we can reduce this.

Before:
![image](https://user-images.githubusercontent.com/17813469/91375855-c3682500-e7e9-11ea-8c34-a41b0e9b27dd.png)

After:
![image](https://user-images.githubusercontent.com/17813469/91375935-ef83a600-e7e9-11ea-80c8-5b92774939f6.png)

This was using **Aspnetcore 2.2** and **GoogleAuthenticator v2.0.1**
Method that generated the spike: **GenerateSetupCode**

**Comment by flytzen** [comment]
Thank you for reporting this. From memory, I think this is a call-out to another lib. Let us have a look...

**Comment by ahwm** [comment]
You are correct, @flytzen - it's using [QRCoder](https://github.com/codebude/QRCoder) for the QR generation.

**Comment by eramosr16** [comment]
I appreciate your quick response guys, keep up the good work. 
If you don't mind let me know when this is out to update my references over here.

**Comment by flytzen** [comment]
@BrandonPotter v2.0.2 is ready for you to approve in AzDO

**Comment by eramosr16** [comment]
Hey guys, while I was waiting for your release I went ahead and clone the repo and built the package myself. I tested again and it seems the library upgrade didn't fix the issue:

![image](https://user-images.githubusercontent.com/17813469/91483256-674ae280-e875-11ea-8b03-e6ce6276f1dc.png)

After finishing the call the memory went down to: 

![image](https://user-images.githubusercontent.com/17813469/91483338-8f3a4600-e875-11ea-8aaa-95421d6fbb32.png)

Just to stay there, perhaps the issue is on the dependency. 
Replacing it with a more efficient one might be a possible solution.

Have a great day.

**Comment by flytzen** [comment]
Ah that sucks. Okay, we'll dig into it some more. @ahwm I'll try to do some profiling and stuff to see if we can narrow it down.

**Comment by ahwm** [comment]
Sounds good. Let me know what you're able to find. I was toying with the idea of setting up a basic API that would allow the QR creation to be offloaded. If it's a completely open source web service that doesn't store anything and uses POST so that data in URLs isn't logged (the primary security concern for TOTP QR generation) then it should be all good. In theory.

In the meantime, I'll see if there are any other libraries out there that would be able to generate them.

**Comment by ahwm** [comment]
https://github.com/BrandonPotter/GoogleAuthenticator/tree/Net.Codecrete.QrCodeGenerator Uses a different library.

**Comment by eramosr16** [comment]
This is the endpoint, I had to hide sensitive information, sorry about that.

![image](https://user-images.githubusercontent.com/17813469/91498442-c0bf0b80-e88d-11ea-8244-2587863e3b8d.png)

**Comment by ahwm** [comment]
You're totally fine. I was most interested in that last parameter. I think that's the issue. When I use 250 I get a gigantic (14,250x14,250 pixels) image that is 1.6 MB.
![image](https://user-images.githubusercontent.com/20478373/91498911-d4fb0c80-e87d-11ea-9002-8702c4799298.png)

When I use 3 in that parameter I get this:
![image](https://user-images.githubusercontent.com/20478373/91499093-21dee300-e87e-11ea-9b18-3add49530434.png)

**Comment by ahwm** [comment]
Similar to #47

**Comment by eramosr16** [comment]
> You're totally fine. I was most interested in that last parameter. I think that's the issue. When I use 250 I get a gigantic (14,250x14,250 pixels) image that is 1.6 MB.
> ![image](https://user-images.githubusercontent.com/20478373/91498911-d4fb0c80-e87d-11ea-9002-8702c4799298.png)
> 
> When I use 3 in that parameter I get this:
> ![image](https://user-images.githubusercontent.com/20478373/91499093-21dee300-e87e-11ea-9b18-3add49530434.png)

I agree with you, I'll update to a lower value and test, but do you think that will also justify the jump from 140 Mb to 1.7 Gb of Memory?.

**Comment by ahwm** [comment]
I don’t know. It’s worth a try and see how big a difference it makes.

**Comment by eramosr16** [comment]
@ahwm I did a test reducing the number from 250 to 50 and the difference was huge it went from 1.7Gb to 300Mb, it seems the issue is there, I went and download the QR library Code and they have a double loop when they go and render the image, which will increase depending on the amount of pixels, offsets and another bunch of variables. They also had a ticket to fix that, I realize that library also had a very poor support this year checking the activity the last update was on April. 

I think you can close this ticket since is not related with you directly, I appreciate all your effort to fix this and your feedback.
Keep up the good work.
Best.
