### ISSUE TITLE
crashes on Linux

### ISSUE THREAD

**Issue by martynas-m** [BrandonPotter/GoogleAuthenticator#57]
while trying to generate qr code following crash occurs:
```
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Graphics.FillRectangle(Brush brush, Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Drawing.Graphics.FillRectangle(Brush brush, Rectangle rect)
   at QRCoder.QRCode.GetGraphic(Int32 pixelsPerModule, Color darkColor, Color lightColor, Boolean drawQuietZones)
   at QRCoder.QRCode.GetGraphic(Int32 pixelsPerModule)
```
not very helpful exception, maybe you need some more details?

**Comment by ahwm** [comment]
More details would certainly be helpful. The problem does seem to be with the QRCoder library instead, though. But maybe it's just a matter of targeting? Which version of .NET are you targeting?

**Comment by martynas-m** [comment]
I'm targeting .net core 3.1, and stack trace shows that error is at QRCoder namespace (as you noted in your previous post)
Probably you've missed, but all action is on Linux (bug title)

**Comment by flytzen** [comment]
I did a quick test on Ubuntu 18.04 and when `libgdiplus` is *missing* I get a type initialisation error. Your stack trace looks like you are getting further.
I suspect you are probably missing one of the other references mentioned by @ahwm. However, when I install only libgdiplus it works, so I am stuck. 
What version of linux are you on? If you are on docker, can you give us a repo?

**Comment by ahwm** [comment]
@flytzen I have the 2.1 release drafted. Are we good to publish that and push to nuget?

**Comment by flytzen** [comment]
@ahwm yes, I believe so. I think we need @BrandonPotter to approve it?

**Comment by ahwm** [comment]
Yeah, that happen in Azure. I'll go ahead and publish, then, and then once it's approved in Azure it will go to nuget.

**Comment by flytzen** [comment]
The "publish" happens automatically when we merge to master - it's sat there waiting for @BrandonPotter already :)

**Comment by flytzen** [comment]
ps if you want to comm more directly, find me on @flytzen on twitter

**Comment by martynas-m** [comment]
I'm using very bare Arch Linux installation.
I was missing `libgdiplus` too, but after installing it still getting crash.
I've checked about using `System.Drawing.*` on Linux a bit, it seems `libgdiplus` is the only dependency needed ( [this source](https://www.vertexfragment.com/ramblings/system-drawing-net-core-linux/) )

I've also did following test to see if image can be generated on linux, and it works on my machine too:

``` c#
var bmp = new Bitmap(100, 100);
var graphics = Graphics.FromImage(bmp);
graphics.DrawEllipse(Pens.Blue, new Rectangle(10, 10, 80, 80));

bmp.Save("test.bmp");
```

so it seems that `System.Graphics` works, but some other dependencies are missing and (most likely) `QRCoder` library is crashing.

I've also checked other dependencies they've mentioned, but I could not find them in my distro. But anyway, since my example is working (I can open saved bitmap) the problem might be somewhere else.

**Comment by flytzen** [comment]
Just one thought - what value are you passing for the `QRPixelsPerModule` parameter? 
Does it crash if you pass in, say 2?

**Comment by martynas-m** [comment]
@flytzen - not sure if question was to me, but I've tried to use `QRCoder` library alone and see if it crashes. This is code I've ran: 
```c#
var qrGenerator = new QRCodeGenerator();
var payloadGenerator = new PayloadGenerator.Url("https://github.com/codebude/QRCoder/");
var qrCodeData = qrGenerator.CreateQrCode(payloadGenerator, QRCodeGenerator.ECCLevel.Q);
			
var pngQrCode = new PngByteQRCode(qrCodeData);
var qrBytes = pngQrCode.GetGraphic(10);
			
File.WriteAllBytes("qr.png", qrBytes);
			
var base64QrCode= new Base64QRCode(qrCodeData);
var qrString = base64QrCode.GetGraphic(10);
File.WriteAllText("qr.html", 
  $"<html><body><img src=\"data:image/png;base64,{qrString}\" alt=\"qr\"/></body></html>");
```

as you see, I've tried to generate qr code as PNG and as base64 (which, I assume, you're using in your library. But this code works and I can open both png and generated html, and scanning from phone also works.

So my earlier assumption that problem was in `QRCoder` seems to be wrong.

**Comment by flytzen** [comment]
@martynas-m Sorry, yes, the question was indeed to you :) 
Thank you for looking into this deeper.
When you call `GenerateSetupCode`, what values do you pass in? Most importantly, what value do you pass in for `QRPixelsPerModule`?

**Comment by martynas-m** [comment]
Hi, 
I think that's was the problem- I was using value 500 (I've looked in description on [description site](https://csharprookie.wordpress.com/2015/03/17/implementing-free-two-factor-authentication-in-net-using-google-authenticator/) and since it showed values passed 300, 300 (which, i guess was width and height) I somehow assumed that this parameter should also be width of qr code. Apparently it was not :) 

So when I've chose to use some reasonable value  like 10, it stopped crashing and works fine. 

Maybe you could make error handling a bit better or just update documentation :)

Thanks for your help, and sorry for false alarm.

**Comment by flytzen** [comment]
Thank you @martynas-m. This is the second time we have seen this so we definitely need to improve this with both docs and error handling. Thank you for raising it.

**Comment by flytzen** [comment]
Need to:
1. Update the readme
2. Make the intellisense much clearer about the importance of this param
3. Possible provide a `default` value to serve as a hint
4. If possible, catch the exception and provide a meaningful error

**Comment by ahwm** [comment]
That documentation @martynas-m linked to is a mirror of an old blog post for how to use the 1.x version that used the Google Charts API. Unfortunately, we don't have direct access. But the link was provided in #21 so it may be possible to reach out and get that updated. I think it would be better to indicate in the readme that it's for 1.x and doesn't apply to 2.x.

**Comment by flytzen** [comment]
@ahwm I agree. I think we need to copy the documentation from that blog post to the readme. I have opened issue #59 to handle that.

**Comment by ahwm** [comment]
In another branch I just specified that it was for 1.x: https://github.com/BrandonPotter/GoogleAuthenticator/commit/28804161d6ae6d4bbd5e2a05bf0559c2211d115b

**Comment by ahwm** [comment]
@BrandonPotter any chance of approving at least the latest nuget package?
