### ISSUE TITLE
Azure Pipelines status badge doesn't show up

### ISSUE THREAD

**Issue by ahwm** [BrandonPotter/GoogleAuthenticator#61]
I was able to figure out that if you're not logged in it gives an error as the response. If I hit the pipelines page and get logged in, then I can see the badge.

https://dev.azure.com/brandon-potter/GoogleAuthenticator/_apis/build/status/BrandonPotter.GoogleAuthenticator?branchName=master

```
{"count":1,"value":{"Message":"Build pipeline BrandonPotter.GoogleAuthenticator was not found."}}
```

Any ideas, @flytzen ?

**Comment by flytzen** [comment]
Ah, yes, I did notice that. I think something has changed. I'll take a look.

**Comment by flytzen** [comment]
The issue is that the project in AzDO is *private*. It needs to be set to *public* so the world can view it. @BrandonPotter - are you able to change this?

**Comment by ahwm** [comment]
While we're making changes to the project there, I propose disabling the approval check since at least three versions now have not been approved to be pushed to Nuget (timeouts after 30 days).

**Comment by BrandonPotter** [comment]
Changed to public, check now?

**Comment by ahwm** [comment]
The badge is visible now.
