### ISSUE TITLE
Release 2.1.1

### ISSUE THREAD

**Issue by flytzen** [BrandonPotter/GoogleAuthenticator#62]
As @ahwm pointed out, the last few releases have not been deployed to Nuget and the releases have expired in AzDO.
Would you be able to run a release to get it deployed please @BrandonPotter?

**Comment by ahwm** [comment]
This seems unlikely. I'm taking @BrandonPotter's "thumbs up" here: https://github.com/BrandonPotter/GoogleAuthenticator/issues/61#issuecomment-729244021 as his vote in the affirmative of removing that criteria. Do you agree @flytzen?

**Comment by BrandonPotter** [comment]
Oops, sorry I missed this - but am highly in favor of removing roadblocks to get the new PR's out the door!

**Comment by flytzen** [comment]
> This seems unlikely. I'm taking @BrandonPotter's "thumbs up" here: [#61 (comment)](https://github.com/BrandonPotter/GoogleAuthenticator/issues/61#issuecomment-729244021) as his vote in the affirmative of removing that criteria. Do you agree @flytzen?

Sorry, what? :D 

The pipeline is public so anyone can read it. But each release currently has to be manually approved by @BrandonPotter in AzDO. We could;
1. Remove that requirement (which means every push to Master is automatically deployed to Nuget)
or;
2. Give @ahwm the rights to approve deploys in AzDO (not sure how easy that is)  
or;
3. Set up a new AzDO free OOS organisation for this library and give ownership to the maintainers. That would also require sharing ownership of the Nuget package.

**Comment by ahwm** [comment]
I don't see any issues with 1. If we only increment the version number when we're ready for a release, then each push to nuget will simply fail as a duplicate. Direct commits to master are prohibited (as a protected branch) and pull requests require review from at least one of the three of us. I think we can manage this rather easily myself.

Alternatively, we could update it to only deploy on tags (at least I assume we can do that with AzDO, I know AppVeyor can behave that way).

**Comment by ahwm** [comment]
Since we all seem to be in agreement, I updated the job and pushed out the 2.1.1 release.
