### ISSUE TITLE
Not generating QR Code in Linux

### ISSUE THREAD

**Issue by SabirHossain** [BrandonPotter/GoogleAuthenticator#63]
I'm using GoogleAuthenticator version 2.1.1 it's working fine on local Windows machine but when I publish it on Linux the QR code is notgenerated anymore.
Before I was using version 2.0.0 that Time I had the below Exception 

`System.TypeInitializationException: The type initializer for 'Gdip' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies`

Then I upgraded the Sysytem.Drawing to 5.0.0 and upgraded GoogleAuthenticator to 2.1.1 after that it's not giving any Exception in Linux server but no QR Code is generated.

on the web I found a solution like below, not sure if it works.

`# install System.Drawing native dependencies
RUN apt-get update \
&& apt-get install -y --allow-unauthenticated \
libc6-dev \
libgdiplus \
libx11-dev \
&& rm -rf /var/lib/apt/lists/*`

**Comment by flytzen** [comment]
Does the information in the readme about `libgdiplus` help?
