### ISSUE TITLE
ValidateTwoFactorPin always returns false, if the secretKey parameter is base32 encoded string

### ISSUE THREAD

**Issue by caterina-novak** [BrandonPotter/GoogleAuthenticator#65]
ValidateTwoFactorPin always returns false, if the secretKey parameter is base32 encoded string. It happens because this parameter is always converted to a byte array in the GenerateHashedCode method using Encoding.UTF8.GetBytes method.
In the case of base32 encoded string, we need to use the method Base32Encoding.ToBytes.

**Comment by ahwm** [comment]
Addressed in #66
