### ISSUE TITLE
Update NuGet API key

### ISSUE THREAD

**Issue by ahwm** [BrandonPotter/GoogleAuthenticator#67]
@BrandonPotter we need you to update the NuGet API key in Pipelines.

Message received:

> The specified API key is invalid, has expired, or does not have permission to access the specified package.

**Comment by ahwm** [comment]
@BrandonPotter pinging reminder. 🙂

**Comment by BrandonPotter** [comment]
Updated!

**Comment by ahwm** [comment]
Pushed and being indexed! 🎉
