### ISSUE TITLE
System.Drawing.Common dependency / .Net 6.0 support

### ISSUE THREAD

**Issue by alex-jitbit** [BrandonPotter/GoogleAuthenticator#69]
You rely on System.Drawing.Common (via QRCoder) which has known issues on Linux and will be removed (marked as platform-specific) in .NET 6.0 here the official announcement  https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

**Comment by flytzen** [comment]
So it looks like #102 solves this - at least for now - and makes it run on .Net 6 on both Windows and Linux. 
I am not really sure as to how. Maybe @tristanboland's change to use `PngByteQRCode` uses a different code path in QR coder that does not rely on System.Drawing. 
@ahwm If correct, then we can probably close this as well once we release the fix in #102? Or do we need to dig into this a bit more to make sure?

**Comment by flytzen** [comment]
Fixed in #102.
Will be released in 2.5 - see #104
