### ISSUE TITLE
Hardcoded dependency to QRCoder 1.4.1?

### ISSUE THREAD

**Issue by ericberman** [BrandonPotter/GoogleAuthenticator#71]
Looks like QRCoder just upgraded to 1.4.2 the other day; now I get this error when loading GoogleAuthenticator:

System.IO.FileLoadException: 'Could not load file or assembly 'QRCoder, Version=1.4.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

If I use nuget to downgrade QRCoder to 1.4.1, it works.

Also seeing this in the decompilation of TwoFactorAuthenticator.cs in visual studio:
Resolve: 'QRCoder, Version=1.4.1.0, Culture=neutral, PublicKeyToken=null'
Found single assembly: 'QRCoder, Version=1.4.2.0, Culture=neutral, PublicKeyToken=c4ed5b9ae8358a28'
WARN: Version mismatch. Expected: '1.4.1.0', Got: '1.4.2.0'
Load from: 'C:\Users\ericb\Documents\logbook\packages\QRCoder.1.4.2\lib\net40\QRCoder.dll'

**Comment by ahwm** [comment]
QRCoder 1.4.1 is a project dependency so the library was built against that version. If you are working on a .NET Framework project you can add a `bindingRedirect` of 1.4.1 to 1.4.2.

```xml
<runtime>
    <dependentAssembly>
        <assemblyIdentity name="QRCoder" publicKeyToken="c4ed5b9ae8358a28" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.4.2.0" newVersion="1.4.2.0" />
    </dependentAssembly>
</runtime
```

I've done this a few times when different libraries have conflicting version dependencies. If there's a compelling reason to target 1.4.2 vs 1.4.1 we'll certainly update that dependency, though.

**Comment by ericberman** [comment]
Tried that, both as above (directly inside the runtime tag) and also inside an assemblybinding tag (where all of my other bindingredirects in webconfig reside), as below:

```
  <runtime xmlns="">
	  <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
		  <dependentAssembly>
			  <assemblyIdentity name="QRCoder" publicKeyToken="c4ed5b9ae8358a28" culture="neutral" />
			  <bindingRedirect oldVersion="0.0.0.0-1.4.2.0" newVersion="1.4.2.0" />
		  </dependentAssembly>
```

Code still fails here:

```
TwoFactorAuthenticator tfa = new TwoFactorAuthenticator();
            SetupCode setupInfo = tfa.GenerateSetupCode(...);
```
I'm running ASP.NET Webforms, targeting 4.6.1

**Comment by ahwm** [comment]
Ah, it looks like 1.4.2 introduced the strong name signing so the bindingredirect might not work. That is also what solidly broke 1.4.1 to 1.4.2 dependency (the `publicKeyToken`s were different)

**Comment by ericberman** [comment]
Works like a charm for me - thanks for the fix and for the rapid turnaround!
