### ISSUE TITLE
Migrate Azure Pipelines to windows-latest

### ISSUE THREAD

**Issue by ahwm** [BrandonPotter/GoogleAuthenticator#73]
Got following warning on pipelines build

```cmd
##[warning]The windows-2016 environment is deprecated and will be removed on March 15, 2022. Migrate to windows-latest instead. For more details, see https://github.com/actions/virtual-environments/issues/4312
```

**Comment by flytzen** [comment]
@ahwm Will sort. I'll take the opportunity to look at a couple of the other outstanding minor issues and then we can release a new version?

**Comment by ahwm** [comment]
> @ahwm Will sort. I'll take the opportunity to look at a couple of the other outstanding minor issues and then we can release a new version?

Sounds good to me
