### ISSUE TITLE
Approvals on push to Nuget

### ISSUE THREAD

**Issue by flytzen** [BrandonPotter/GoogleAuthenticator#76]
@BrandonPotter @ahwm I have just added an "approval" step on the azure pipeline that pushes the new version to Nuget - hope that is okay?
It's just to avoid errors like when the readme changes were merged, we got a report that it had failed to deploy to Nuget because the version number hadn't changed. 
Having an approval step will allow us a bit of breathing space to merge multiple PRs before we push a new version to Nuget.
If I have set it up correctly, all three of us have been set up to approve so either of us can do it.

Also, would be nice to be able to chat outside of issues :) If you use Twitter, can you ping me @flytzen?

**Comment by BrandonPotter** [comment]
That is great - thanks!

Twitter @brandonpotter - not active but lemme find my app and DM you later!

**Comment by ahwm** [comment]
Sounds good! I think I may have created a Twitter account years ago, but never used it. I primarily use Discord and Google Chat these days, but I'll see if I can find details.

**Comment by BrandonPotter** [comment]
I have discord!

**Comment by ahwm** [comment]
ahwm#2675 on Discord

**Comment by ahwm** [comment]
@flytzen it looks like all three of us have to approve it in sequence now.

**Comment by flytzen** [comment]
Ah, sorry, it's been too long. Lemme fix it.

**Comment by flytzen** [comment]
Bloody hell, didn't see the rest of what you wrote, sorry 🤣
Thank you for fixing.

**Comment by flytzen** [comment]
> I primarily use Discord

All the cool kids use Discord - I really need to get onboard with that :D
