### ISSUE TITLE
Add DependaBot

### ISSUE THREAD

**Issue by flytzen** [BrandonPotter/GoogleAuthenticator#79]
We should add DependaBot and update dependencies before the next release:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-dependabot-version-updates

This *should* also pick up when a release comes out that fixes #69

**Comment by flytzen** [comment]
@ahwm You happy with this suggestion? I should be able to find an example file from another project and drop it in.

**Comment by ahwm** [comment]
I have Dependabot configured on some of my projects already as well so I could throw one in super fast.
