### ISSUE TITLE
HMACSHA1 algorithm defaults to non-FIPS compliant implementation

### ISSUE THREAD

**Issue by briantshock** [BrandonPotter/GoogleAuthenticator#8]
I ran into an issue with the code throwing an InvalidOperationException when calling ValidateTwoFactorPIN on a machine with the "System cryptography: Use FIPS compliant algorithms for encryption, hashing, and signatures" Local Policy set to Enabled (default is Disabled). As we have some sites dealing potentially with federal data we need to leave this on for compliance reasons.

I traced the issue down to line 182 in `internal string GenerateHashedCode(byte[] key, long iterationNumber, int digits = 6)` where the SHA1 cryptography was being created.

`HMACSHA1 hmac = new HMACSHA1(key, true);`

According to [https://msdn.microsoft.com/en-us/library/ms223095(v=vs.110).aspx](https://msdn.microsoft.com/en-us/library/ms223095(v=vs.110).aspx), the second parameter indicates whether to use the managed implementation of the SHA1 algorithm – true uses SHA1Manager and false uses SHA1CryptoServiceProvider. Apparently SHA1Manager is not FIPS compliant but SHA1CryptoServiceProvider is.

I think this second parameter should be configurable to allow the user to specify using the managed SHA1 class or not.

**Comment by BrandonPotter** [comment]
Good catch. Want to make this a configurable property and do a PR? I wonder if this would be worth a check in the constructor to throw an exception when the machine does not support SHA1Manager?

**Comment by briantshock** [comment]
Sure, I'd be happy to. I think the constructor check is a good idea - do
you think it should swallow the exception and default to the unmanaged
class, or throw the exception back out for the user to decide?

**Comment by BrandonPotter** [comment]
The spirit of the library is "easy and just works". So I would say if the managed provider fails to instantiate, try the unmanaged provider. If the unmanaged provider works then swallow and set unmanaged as default.

If the unmanaged also fails (if user does it allow unmanaged code etc) then throw it back for the user to deal with it since there's no way it's going to work.

**Comment by BrandonPotter** [comment]
If user doesn't allow*

**Comment by briantshock** [comment]
I've checked in the fix we discussed to my master branch and created a PR. I tested it out on our test environment by dropping the updated DLL directly into the project and everything worked fine. We no longer got the FIPS compliant issue thrown.

**Comment by BrandonPotter** [comment]
Great, merged and package should be updated now. Thanks!!

**Comment by BrandonPotter** [comment]
Package *should* be updated, hmm

**Comment by briantshock** [comment]
I didn't touch any of the AssemblyInfo.. maybe nuget doesn't think it's
changed?

**Comment by BrandonPotter** [comment]
CI build issue, should be published now. Thanks!
