### ISSUE TITLE
Missing ...else { throw; } ?

### ISSUE THREAD

**Issue by flytzen** [BrandonPotter/GoogleAuthenticator#85]
Looking at the QR generation code because of issue #50 and came across this:
https://github.com/BrandonPotter/GoogleAuthenticator/blob/f0f1143b82d54f867977ab06e6d4d9dd93c77925/Google.Authenticator/TwoFactorAuthenticator.cs#L104

shouldn't we have
```
else { throw; }
```
in this one and the one below to avoid swallowing exceptions?

**Comment by ahwm** [comment]
That's probably a good idea.
