### ISSUE TITLE
Release v 2.4

### ISSUE THREAD

**Issue by flytzen** [BrandonPotter/GoogleAuthenticator#90]
Once #88  is approved, should we release v2.4 to get the latest improvements out there?

**Comment by ahwm** [comment]
#91  increments the version to 2.4

**Comment by flytzen** [comment]
@ahwm do you want to do the honours and approve the release on DevOps?

**Comment by ahwm** [comment]
Looks like the interface won’t let me do it from my phone so once I find a computer I’ll do that.

**Comment by ahwm** [comment]
@flytzen Deployed and the readme looks great on the NuGet page. 🙂
