### ISSUE TITLE
.NET Core 6 support

### ISSUE THREAD

**Issue by Revsgaard** [BrandonPotter/GoogleAuthenticator#98]
Hi,

Wondering if or when .NET Core 6 is supported, because .NET Core 6 is LTS version and .NET Core 5 is end of support in May.

Thanks

**Comment by ahwm** [comment]
Waiting for QRCoder - see #69

**Comment by hez2010** [comment]
Workaround: https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action

**Comment by naviln** [comment]
Any update on this? Would love to see .Net Core 6 support!

**Comment by flytzen** [comment]
Fixed in #102.
Will be released in 2.5. See #104
